version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
#    networks:
#      new:
#        aliases:
#          - database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ordent_marketplace
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    networks:
#      - new
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/ordent_marketplace?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
#  migrate:
#    image: migrate/migrate
##    networks:
##      - new
#    volumes:
#      - .:/migrations
#    command: [ "-path", "/migrations", "-database",  "postgresql://root:secret@postgres:5432/ordent_marketplace?sslmode=disable", "up", "1" ]
#    depends_on:
#      - postgres
##networks:
##  new: