// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID       int32         `json:"id"`
	Name     string        `json:"name"`
	ParentID sql.NullInt32 `json:"parent_id"`
}

type Country struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Merchant struct {
	ID          int32     `json:"id"`
	AdminID     int32     `json:"admin_id"`
	Name        string    `json:"name"`
	CountryCode string    `json:"country_code"`
	CreatedAt   time.Time `json:"created_at"`
}

type Order struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type OrderItem struct {
	OrderID   int32 `json:"order_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

type Product struct {
	ID         int32     `json:"id"`
	Name       string    `json:"name"`
	MerchantID int32     `json:"merchant_id"`
	Price      int32     `json:"price"`
	Status     string    `json:"status"`
	CategoryID int32     `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                int32     `json:"id"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	CountryCode       string    `json:"country_code"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
